#!/usr/bin/env python3
"""Render the public API reference from docstrings into docs/api.md.

The reference is generated from the library's public docstrings via pydoc-markdown
(see `pydoc-markdown.yml`). Docstrings are the single source of truth; the README
links to the generated file rather than duplicating it.

Usage:
    python scripts/gen_api_docs.py            # regenerate docs/api.md
    python scripts/gen_api_docs.py --check    # exit non-zero if docs/api.md is stale

The `--check` mode runs as a pre-commit hook so the file can never drift from the
docstrings.
"""

import argparse
import contextlib
import difflib
import io
import os
import sys
from pathlib import Path

import yaml
from pydoc_markdown import PydocMarkdown
from pydoc_markdown.interfaces import Context

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "pydoc-markdown.yml"
OUTPUT = REPO_ROOT / "docs" / "api.md"

HEADER = (
    "<!-- Generated by scripts/gen_api_docs.py from the library's docstrings. Do not "
    "edit by hand; run `make apidocs`. -->\n\n"
    "# API Reference\n\n"
)


def render() -> str:
    """Runs pydoc-markdown and returns the full docs/api.md contents as a string."""
    config = yaml.safe_load(CONFIG.read_text())
    session = PydocMarkdown()
    session.load_config(config)
    session.init(Context(directory=str(REPO_ROOT)))
    modules = session.load_modules()
    session.process(modules)
    # The markdown renderer writes to stdout; capture it rather than a temp file.
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        session.render(modules)
    return HEADER + buf.getvalue().strip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero (without writing) if docs/api.md is out of date",
    )
    args = parser.parse_args()

    generated = render()
    current = OUTPUT.read_text() if OUTPUT.exists() else ""

    if generated == current:
        return 0

    if args.check:
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile="docs/api.md (current)",
            tofile="docs/api.md (regenerated)",
        )
        sys.stdout.writelines(diff)
        print(
            "\nerror: docs/api.md is out of date. Run `make apidocs` and commit the result.",
            file=sys.stderr,
        )
        return 1

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated)
    print(f"wrote {os.path.relpath(OUTPUT, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
